### ISSUE TITLE
每个电台的曲目限制

### ISSUE THREAD

**Issue by SamLukeYes** [GuGuMur/MusicFreePlugin-NeteaseRadio#1]
目前这个插件每个电台最多只能加载 30 个曲目。这个值似乎是在这里定义的：

https://github.com/GuGuMur/MusicFreePlugin-NeteaseRadio/blob/9bff73396f0c7a80f4a2ece7cec1526bb4632943/src/index.ts#L100

然后在这里限制了每个电台的曲目：

https://github.com/GuGuMur/MusicFreePlugin-NeteaseRadio/blob/9bff73396f0c7a80f4a2ece7cec1526bb4632943/src/index.ts#L204-L209

目前在本地作了如下尝试：

1. 将 `pageSize` 的值改为 1000，无法加载搜索结果
2. 注释掉 208 行，每个电台只能加载 10 个曲目
3. 将 208 行改为 `limit: 1000`，实际观察到的上限是 500，曲目多于 500 的电台仍然无法全部加载

希望能有办法解除这个限制，比如通过多次请求加载曲目多于 500 的电台？

**Comment by GuGuMur** [comment]
改好了（
